package View;

import Controller.ProdutoController;
import java.awt.event.WindowAdapter;
import javax.swing.JOptionPane;

public class CadastroProduto extends javax.swing.JDialog {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLabel = new javax.swing.JLabel();
        fornecedorLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        precoVendaLabel = new javax.swing.JLabel();
        precoCompraLabel = new javax.swing.JLabel();
        codigoProdutoInput = new javax.swing.JTextField();
        fornecedorProdutoInput = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        nomeProdutoInput = new javax.swing.JTextField();
        precoVendaProdutoInput = new javax.swing.JTextField();
        precoCompraProdutoInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoProdutoInput = new javax.swing.JTextArea();
        findFornecedor = new javax.swing.JButton();
        cancelarCadastroProduto = new javax.swing.JButton();
        confirmarCadastroProduto = new javax.swing.JButton();
        separadorFooter = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setResizable(false);

        codigoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoLabel.setText("Código:*");

        fornecedorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fornecedorLabel.setText("Fornecedor:*");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome:*");

        descricaoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricaoLabel.setText("Descrição:*");

        precoVendaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoVendaLabel.setText("Preço Venda:*");

        precoCompraLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoCompraLabel.setText("Preço Compra:");

        codigoProdutoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoInputActionPerformed(evt);
            }
        });

        fornecedorProdutoInput.setEditable(false);
        fornecedorProdutoInput.setBackground(new java.awt.Color(206, 211, 208));

        jTextField3.setText("jTextField1");

        precoVendaProdutoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoVendaProdutoInputActionPerformed(evt);
            }
        });

        descricaoProdutoInput.setColumns(20);
        descricaoProdutoInput.setRows(5);
        jScrollPane1.setViewportView(descricaoProdutoInput);

        findFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/findIcon.png"))); // NOI18N
        findFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFornecedorActionPerformed(evt);
            }
        });

        cancelarCadastroProduto.setBackground(new java.awt.Color(255, 51, 51));
        cancelarCadastroProduto.setText("Cancelar");
        cancelarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastroProdutoActionPerformed(evt);
            }
        });

        confirmarCadastroProduto.setBackground(new java.awt.Color(0, 153, 0));
        confirmarCadastroProduto.setText("Cadastrar");
        confirmarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorFooter, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(precoVendaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoVendaProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(precoCompraLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoCompraProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeLabel)
                            .addComponent(fornecedorLabel)
                            .addComponent(descricaoLabel)
                            .addComponent(codigoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fornecedorProdutoInput)
                                .addGap(18, 18, 18)
                                .addComponent(findFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(codigoProdutoInput)
                            .addComponent(nomeProdutoInput)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelarCadastroProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarCadastroProduto)
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fornecedorLabel)
                            .addComponent(fornecedorProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoVendaLabel)
                    .addComponent(precoVendaProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCompraLabel)
                    .addComponent(precoCompraProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(separadorFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarCadastroProduto)
                    .addComponent(confirmarCadastroProduto))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoProdutoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoInputActionPerformed

    private void precoVendaProdutoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoVendaProdutoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoVendaProdutoInputActionPerformed

    private void cancelarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastroProdutoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarCadastroProdutoActionPerformed

    private void confirmarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarCadastroProdutoActionPerformed
        //Vamos Cadastrar um novo fornecedor;
        boolean valido = true;
        ProdutoController controller = new ProdutoController();
        String codigo = codigoProdutoInput.getText();
        if (codigo.trim().equals("")) {
            valido = false;
        }
        String codigoFornecedor = fornecedorProdutoInput.getText();
        if (codigoFornecedor.trim().equals("")) {
            valido = false;
        }else{
            String[] partes = codigoFornecedor.split("-");
            codigoFornecedor = partes[0];
        }
        String nome = nomeProdutoInput.getText();
        if (nome.trim().equals("")) {
            valido = false;
        }
        String descricao = descricaoProdutoInput.getText();
        if (descricao.trim().equals("")) {
            valido = false;
        }
        String precoCompra = precoCompraProdutoInput.getText();
        if (precoCompra.trim().equals("")) {
            valido = false;
        }
        String precoVenda = precoVendaProdutoInput.getText();
        if (precoVenda.trim().equals("")) {
            valido = false;
        }
      

        if (valido) {
            String mensagem = controller.cadastrarNovoProduto(codigo, codigoFornecedor, nome, descricao, precoCompra, precoVenda);
            JOptionPane.showMessageDialog(null, mensagem);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos, verifique o cadastro");
        }
    }//GEN-LAST:event_confirmarCadastroProdutoActionPerformed

    private void findFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFornecedorActionPerformed
        PesquisarFornecedor pesquisaFornecedor = new PesquisarFornecedor(null, true);
        pesquisaFornecedor.setVisible(true);
        this.fornecedorProdutoInput.setText(pesquisaFornecedor.getRetornaValor());
    }//GEN-LAST:event_findFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroProduto dialog = new CadastroProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCadastroProduto;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoProdutoInput;
    private javax.swing.JButton confirmarCadastroProduto;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoProdutoInput;
    private javax.swing.JButton findFornecedor;
    private javax.swing.JLabel fornecedorLabel;
    private javax.swing.JTextField fornecedorProdutoInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeProdutoInput;
    private javax.swing.JLabel precoCompraLabel;
    private javax.swing.JTextField precoCompraProdutoInput;
    private javax.swing.JLabel precoVendaLabel;
    private javax.swing.JTextField precoVendaProdutoInput;
    private javax.swing.JSeparator separadorFooter;
    // End of variables declaration//GEN-END:variables
}
