package View;

import Controller.ArquivoController;
import Controller.Constantes;
import Controller.FornecedorController;
import Model.Contato;
import Model.Endereco;
import Model.Fornecedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditarFornecedor extends javax.swing.JDialog {
    Constantes cons = new Constantes();
    Fornecedor fornecedor;

    /**
     * Creates new form EditarFornecedor
     */
    public EditarFornecedor(java.awt.Frame parent, boolean modal, Fornecedor fornecedor) {
        super(parent, modal);
        initComponents();
        this.setFornecedor(fornecedor);
        loadModelToView(fornecedor);
    }

    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

    private void loadModelToView(Fornecedor fornecedor) {
        this.codigoFornecedorInput.setText(fornecedor.getCodigo());
        this.nomeFornecedorInput.setText(fornecedor.getNome());
        this.loginFornecedorInput.setText(fornecedor.getLogin());
        this.senhaFornecedorInput.setText(fornecedor.getSenha());
        this.cnpjFornecedorInput.setText(fornecedor.getCnpj());
        this.nomeFantasiaFornecedorInput.setText(fornecedor.getNomeFatasia());
        this.inscricaoEstadualFornecedorInput.setText(fornecedor.getInscricaoEstadual());
        
        DefaultTableModel tabelaEndereco = (DefaultTableModel) tableEnderecoFornecedor.getModel();
        DefaultTableModel tabelaContato = (DefaultTableModel) tableContatosFornecedor.getModel();
        ArquivoController controller = new ArquivoController();
        
        ArrayList<Endereco> enderecos = controller.getEnderecosByCodigoPai(cons.getPATH_PART_INITIAL()+cons.getENDERECO_FORNECEDOR(), fornecedor.getCodigo(), cons.getTIPO_FORNECEDOR());
        for(Endereco endereco : enderecos){
            tabelaEndereco.addRow(new Object[]{endereco.getCodigo(), endereco.getRua(), endereco.getBairro(), endereco.getCidade(), endereco.getEstado(), endereco.getComplemento(), endereco.getReferencia()});
        }
        ArrayList<Contato> contatos = controller.getContatosByCodigoPai(cons.getPATH_PART_INITIAL()+cons.getCONTATO_FORNECEDOR(), fornecedor.getCodigo(), cons.getTIPO_FORNECEDOR());
        for(Contato contato : contatos){
            tabelaContato.addRow(new Object[]{contato.getCodigo(), contato.getTipo(), contato.getConteudo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inscricaoEstadualLabel = new javax.swing.JLabel();
        nomeFantasiaFornecedorInput = new javax.swing.JTextField();
        inscricaoEstadualFornecedorInput = new javax.swing.JTextField();
        addContatoButton = new javax.swing.JButton();
        addEnderecoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContatosFornecedor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnderecoFornecedor = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        confirmarEdicaoFornecedor = new javax.swing.JButton();
        cancelarCadastroFornecedor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        removeEnderecoFornecedor = new javax.swing.JButton();
        separadorFooter = new javax.swing.JSeparator();
        removeContatoFornecedor = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        codigoFornecedorInput = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        loginFornecedorInput = new javax.swing.JTextField();
        nomeFornecedorInput = new javax.swing.JTextField();
        senhaFornecedorInput = new javax.swing.JPasswordField();
        cnpjLabel = new javax.swing.JLabel();
        cnpjFornecedorInput = new javax.swing.JFormattedTextField();
        nomeFantasiaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inscricaoEstadualLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inscricaoEstadualLabel.setText("Inscrição Estadual:*");

        addContatoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addIcon.png"))); // NOI18N
        addContatoButton.setText("Adicionar Contato");
        addContatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContatoButtonActionPerformed(evt);
            }
        });

        addEnderecoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addIcon.png"))); // NOI18N
        addEnderecoButton.setText("Adicionar Endereço");
        addEnderecoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnderecoButtonActionPerformed(evt);
            }
        });

        tableContatosFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Conteudo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableContatosFornecedor);

        tableEnderecoFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Rua", "Bairro", "Cidade", "Estado", "Complemento", "Referência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEnderecoFornecedor);

        jSeparator1.setToolTipText("Ddados de contato");

        confirmarEdicaoFornecedor.setBackground(new java.awt.Color(0, 153, 0));
        confirmarEdicaoFornecedor.setText("Editar");
        confirmarEdicaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEdicaoFornecedorActionPerformed(evt);
            }
        });

        cancelarCadastroFornecedor.setBackground(new java.awt.Color(255, 51, 51));
        cancelarCadastroFornecedor.setText("Cancelar");
        cancelarCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastroFornecedorActionPerformed(evt);
            }
        });

        jSeparator2.setToolTipText("Ddados de contato");

        removeEnderecoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        removeEnderecoFornecedor.setText("Remover Linha Selecionada");
        removeEnderecoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnderecoFornecedorActionPerformed(evt);
            }
        });

        removeContatoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        removeContatoFornecedor.setText("Remover Linha Selecionada");
        removeContatoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeContatoFornecedorActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome:*");

        codigoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoLabel.setText("Codigo:*");

        loginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginLabel.setText("Login:*");

        codigoFornecedorInput.setEditable(false);
        codigoFornecedorInput.setBackground(new java.awt.Color(206, 211, 208));

        senhaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senhaLabel.setText("Senha:*");

        cnpjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnpjLabel.setText("CPNJ:*");

        try {
            cnpjFornecedorInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        nomeFantasiaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeFantasiaLabel.setText("Nome Fantasia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorFooter)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addContatoButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeContatoFornecedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addEnderecoButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeEnderecoFornecedor))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelarCadastroFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarEdicaoFornecedor)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addGap(18, 18, 18)
                        .addComponent(loginFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senhaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(senhaFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cnpjLabel)
                            .addComponent(nomeFantasiaLabel)
                            .addComponent(inscricaoEstadualLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inscricaoEstadualFornecedorInput)
                            .addComponent(nomeFantasiaFornecedorInput)
                            .addComponent(cnpjFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoLabel)
                            .addComponent(nomeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(codigoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codigoFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeFornecedorInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjLabel)
                    .addComponent(cnpjFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFantasiaLabel)
                    .addComponent(nomeFantasiaFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscricaoEstadualLabel)
                    .addComponent(inscricaoEstadualFornecedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addContatoButton)
                    .addComponent(removeContatoFornecedor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnderecoButton)
                    .addComponent(removeEnderecoFornecedor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separadorFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarCadastroFornecedor)
                    .addComponent(confirmarEdicaoFornecedor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContatoButtonActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tableContatosFornecedor.getModel();
        if (tabela.getRowCount() < 10) {
            tabela.addRow(new Object[]{"", "", ""});
        } else {
            JOptionPane.showMessageDialog(null, "Limite de 10 Contatos por fornecedor");
        }
    }//GEN-LAST:event_addContatoButtonActionPerformed

    private void addEnderecoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnderecoButtonActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tableEnderecoFornecedor.getModel();
        if (tabela.getRowCount() < 5) {
            tabela.addRow(new Object[]{"", "", "", "", "", "", ""});
        } else {
            JOptionPane.showMessageDialog(null, "Limite de 5 Endereços por fornecedor");
        }
    }//GEN-LAST:event_addEnderecoButtonActionPerformed

    private void confirmarEdicaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEdicaoFornecedorActionPerformed
        //Vamos Cadastrar um novo fornecedor;
        boolean valido = true;
        FornecedorController controller = new FornecedorController();
        String codigo = codigoFornecedorInput.getText();
        if (codigo.trim().equals("")) {
            valido = false;
        }
        String nome = nomeFornecedorInput.getText();
        if (nome.trim().equals("")) {
            valido = false;
        }
        String login = loginFornecedorInput.getText();
        if (login.trim().equals("")) {
            valido = false;
        }
        String senha = senhaFornecedorInput.getText();
        if (senha.trim().equals("")) {
            valido = false;
        }
        String cnpj = cnpjFornecedorInput.getText();
        if (cnpj.trim().equals("")) {
            valido = false;
        }
        String nomeFantasia = nomeFantasiaFornecedorInput.getText();
        String inscricaoEstadual = inscricaoEstadualFornecedorInput.getText();
        if (inscricaoEstadual.trim().equals("")) {
            valido = false;
        }
        DefaultTableModel tabelaEndereco = (DefaultTableModel) tableEnderecoFornecedor.getModel();
        String[][] enderecos = new String[tabelaEndereco.getRowCount()][7];
        //Vamos buscar nossas informacoes da tabelaEndereco, cada count representa uma row e 0,1,2...5 sao as colunas

        for (int row = 0; row < tabelaEndereco.getRowCount(); row++) {
            if (tabelaEndereco.getValueAt(row, 0) != "") {
                enderecos[row][0] = tabelaEndereco.getValueAt(row, 0).toString();
            } else {
                enderecos[row][0] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 1) != "") {
                enderecos[row][1] = tabelaEndereco.getValueAt(row, 1).toString();
            } else {
                enderecos[row][1] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 2) != "") {
                enderecos[row][2] = tabelaEndereco.getValueAt(row, 2).toString();
            } else {
                enderecos[row][2] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 3) != "") {
                enderecos[row][3] = tabelaEndereco.getValueAt(row, 3).toString();
            } else {
                enderecos[row][3] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 4) != "") {
                enderecos[row][4] = tabelaEndereco.getValueAt(row, 4).toString();
            } else {
                enderecos[row][4] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 5) != "") {
                enderecos[row][5] = tabelaEndereco.getValueAt(row, 5).toString();
            } else {
                enderecos[row][5] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 6) != "") {
                enderecos[row][6] = tabelaEndereco.getValueAt(row, 6).toString();
            } else {
                enderecos[row][6] = "campoVazio";
            }
        }

        DefaultTableModel tabelaContatos = (DefaultTableModel) tableContatosFornecedor.getModel();
        String[][] contatos = new String[tabelaContatos.getRowCount()][3];
        //Vamos buscar nossas informacoes da tabelaEndereco, cada count representa uma row e 0,1,2...5 sao as colunas
        if (valido) {
            for (int row2 = 0; row2 < tabelaContatos.getRowCount(); row2++) {
                if (tabelaContatos.getValueAt(row2, 0) != "") {
                    contatos[row2][0] = tabelaContatos.getValueAt(row2, 0).toString();
                } else {
                    contatos[row2][0] = "campoVazio";
                }
                if (tabelaContatos.getValueAt(row2, 1) != "") {
                    contatos[row2][1] = tabelaContatos.getValueAt(row2, 1).toString();
                } else {
                    contatos[row2][1] = "campoVazio";
                }
                if (tabelaContatos.getValueAt(row2, 2) != "") {
                    contatos[row2][2] = tabelaContatos.getValueAt(row2, 2).toString();
                } else {
                    contatos[row2][2] = "campoVazio";
                }
            }
        }

        if (valido) {
            String mensagem = controller.editarFornecedor(codigo, nome, login, senha, cnpj, nomeFantasia, inscricaoEstadual, enderecos, contatos);
            JOptionPane.showMessageDialog(null, mensagem);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos, verifique o cadastro");
        }
    }//GEN-LAST:event_confirmarEdicaoFornecedorActionPerformed

    private void cancelarCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastroFornecedorActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarCadastroFornecedorActionPerformed

    private void removeEnderecoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnderecoFornecedorActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableEnderecoFornecedor.getModel();
        try {
            int SelectedRowIndex = tableEnderecoFornecedor.getSelectedRow();
            int SelectedsRows = tableEnderecoFornecedor.getSelectedRowCount();
            if (SelectedsRows == 1) {
                model.removeRow(SelectedRowIndex);
            } else if (SelectedsRows > 1) {
                JOptionPane.showMessageDialog(null, "Para garantir uma exclusão mais segura, selecione apenas um linha por vez");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para exclusão");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_removeEnderecoFornecedorActionPerformed

    private void removeContatoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeContatoFornecedorActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableContatosFornecedor.getModel();
        try {
            int SelectedRowIndex = tableContatosFornecedor.getSelectedRow();
            int SelectedsRows = tableContatosFornecedor.getSelectedRowCount();
            if (SelectedsRows == 1) {
                model.removeRow(SelectedRowIndex);
            } else if (SelectedsRows > 1) {
                JOptionPane.showMessageDialog(null, "Para garantir uma exclusão mais segura, selecione apenas um linha por vez");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para exclusão");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_removeContatoFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarFornecedor dialog = new EditarFornecedor(new javax.swing.JFrame(), true, new Fornecedor());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContatoButton;
    private javax.swing.JButton addEnderecoButton;
    private javax.swing.JButton cancelarCadastroFornecedor;
    private javax.swing.JFormattedTextField cnpjFornecedorInput;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JTextField codigoFornecedorInput;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JButton confirmarEdicaoFornecedor;
    private javax.swing.JTextField inscricaoEstadualFornecedorInput;
    private javax.swing.JLabel inscricaoEstadualLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField loginFornecedorInput;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nomeFantasiaFornecedorInput;
    private javax.swing.JLabel nomeFantasiaLabel;
    private javax.swing.JTextField nomeFornecedorInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton removeContatoFornecedor;
    private javax.swing.JButton removeEnderecoFornecedor;
    private javax.swing.JPasswordField senhaFornecedorInput;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JSeparator separadorFooter;
    private javax.swing.JTable tableContatosFornecedor;
    private javax.swing.JTable tableEnderecoFornecedor;
    // End of variables declaration//GEN-END:variables
}
