package View;

import Controller.ArquivoController;
import Controller.AtendenteController;
import Controller.Constantes;
import Model.Atendente;
import Model.Contato;
import Model.Endereco;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditarAtendente extends javax.swing.JDialog {
    Constantes cons = new Constantes();
    
    Atendente atendente;
    /**
     * Creates new form EditarAtendente
     */
    public EditarAtendente(java.awt.Frame parent, boolean modal, Atendente atendente) {
        super(parent, modal);
        initComponents();
        this.setAtendente(atendente);
        loadModelToView(atendente);
    }   

    public void setAtendente(Atendente atendente) {
        this.atendente = atendente;
    }
    
    private void loadModelToView(Atendente atendente) {
        this.codigoAtendenteInput.setText(atendente.getCodigo());
        this.nomeAtendenteInput.setText(atendente.getNome());
        this.sobrenomeAtendenteInput.setText(atendente.getSobrenome());
        this.loginAtendenteInput.setText(atendente.getLogin());
        this.senhaAtendenteInput.setText(atendente.getSenha());
        this.funcaoAtendenteInput.setText(atendente.getFuncao());
        this.nascimentoAtendenteInput.setText(atendente.getDataNascimento());
        this.admissaoAtendenteInput.setText(atendente.getDataAdmissao());
        
        DefaultTableModel tabelaEndereco = (DefaultTableModel) tableEnderecosAtendente.getModel();
        DefaultTableModel tabelaContato = (DefaultTableModel) tableContatosAtendente.getModel();
        ArquivoController controller = new ArquivoController();
        
        ArrayList<Endereco> enderecos = controller.getEnderecosByCodigoPai(cons.getPATH_PART_INITIAL()+cons.getENDERECO_ATENDENTE(), atendente.getCodigo(), cons.getTIPO_ATENDENTE());
        for(Endereco endereco : enderecos){
            tabelaEndereco.addRow(new Object[]{endereco.getCodigo(), endereco.getRua(), endereco.getBairro(), endereco.getCidade(), endereco.getEstado(), endereco.getComplemento(), endereco.getReferencia()});
        }
        ArrayList<Contato> contatos = controller.getContatosByCodigoPai(cons.getPATH_PART_INITIAL()+cons.getCONTATO_ATENDENTE(), atendente.getCodigo(), cons.getTIPO_ATENDENTE());
        for(Contato contato : contatos){
            tabelaContato.addRow(new Object[]{contato.getCodigo(), contato.getTipo(), contato.getConteudo()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sobrenomeLabel = new javax.swing.JLabel();
        nascimentoAtendenteInput = new javax.swing.JTextField();
        sobrenomeAtendenteInput = new javax.swing.JTextField();
        addContatoButtonAtendente = new javax.swing.JButton();
        addEnderecoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContatosAtendente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnderecosAtendente = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        confirmarEdicaoCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        removeContato = new javax.swing.JButton();
        cancelarCadastroCliente = new javax.swing.JButton();
        removeEndereco = new javax.swing.JButton();
        separadorFooter = new javax.swing.JSeparator();
        codigoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        codigoAtendenteInput = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        nascimentoLabel1 = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        admissaoAtendenteInput = new javax.swing.JTextField();
        loginAtendenteInput = new javax.swing.JTextField();
        funcaoAtendenteInput = new javax.swing.JTextField();
        nomeAtendenteInput = new javax.swing.JTextField();
        senhaAtendenteInput = new javax.swing.JPasswordField();
        cpfLabel = new javax.swing.JLabel();
        nascimentoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sobrenomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sobrenomeLabel.setText("Sobrenome*:");

        addContatoButtonAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addIcon.png"))); // NOI18N
        addContatoButtonAtendente.setText("Adicionar Contato");
        addContatoButtonAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContatoButtonAtendenteActionPerformed(evt);
            }
        });

        addEnderecoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addIcon.png"))); // NOI18N
        addEnderecoButton.setText("Adicionar Endereço");
        addEnderecoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnderecoButtonActionPerformed(evt);
            }
        });

        tableContatosAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Conteudo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableContatosAtendente);

        tableEnderecosAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Rua", "Bairro", "Cidade", "Estado", "Complemento", "Referência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEnderecosAtendente);

        jSeparator1.setToolTipText("Ddados de contato");

        confirmarEdicaoCliente.setBackground(new java.awt.Color(0, 153, 0));
        confirmarEdicaoCliente.setText("Editar");
        confirmarEdicaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEdicaoClienteActionPerformed(evt);
            }
        });

        jSeparator2.setToolTipText("Ddados de contato");

        removeContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        removeContato.setText("Remover Linha Selecionada");
        removeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeContatoActionPerformed(evt);
            }
        });

        cancelarCadastroCliente.setBackground(new java.awt.Color(255, 51, 51));
        cancelarCadastroCliente.setText("Cancelar");
        cancelarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastroClienteActionPerformed(evt);
            }
        });

        removeEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        removeEndereco.setText("Remover Linha Selecionada");
        removeEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnderecoActionPerformed(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoLabel.setText("Codigo:*");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome:*");

        loginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginLabel.setText("Login:*");

        nascimentoLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nascimentoLabel1.setText("Adimissão:*");

        senhaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senhaLabel.setText("Senha:*");

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfLabel.setText("Função:*");

        nascimentoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nascimentoLabel.setText("Nascimento:*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorFooter)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addContatoButtonAtendente)
                                .addGap(18, 18, 18)
                                .addComponent(removeContato))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addEnderecoButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeEndereco))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelarCadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarEdicaoCliente)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfLabel)
                            .addComponent(nascimentoLabel)
                            .addComponent(senhaLabel)
                            .addComponent(loginLabel)
                            .addComponent(sobrenomeLabel)
                            .addComponent(nascimentoLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginAtendenteInput, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                            .addComponent(nascimentoAtendenteInput)
                            .addComponent(senhaAtendenteInput, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                            .addComponent(admissaoAtendenteInput)
                            .addComponent(sobrenomeAtendenteInput, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                            .addComponent(funcaoAtendenteInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoLabel)
                            .addComponent(nomeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeLabel)
                    .addComponent(sobrenomeAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(funcaoAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascimentoLabel)
                    .addComponent(nascimentoAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascimentoLabel1)
                    .addComponent(admissaoAtendenteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addContatoButtonAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnderecoButton)
                    .addComponent(removeEndereco))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separadorFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarCadastroCliente)
                    .addComponent(confirmarEdicaoCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContatoButtonAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContatoButtonAtendenteActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tableContatosAtendente.getModel();
        if (tabela.getRowCount() < 10) {
            tabela.addRow(new Object[]{"", "", ""});
        } else {
            JOptionPane.showMessageDialog(null, "Limite de 10 Contatos por atendente");
        }
    }//GEN-LAST:event_addContatoButtonAtendenteActionPerformed

    private void addEnderecoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnderecoButtonActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tableEnderecosAtendente.getModel();
        if (tabela.getRowCount() < 5) {
            tabela.addRow(new Object[]{"", "", "", "", "", "", ""});
        } else {
            JOptionPane.showMessageDialog(null, "Limite de 5 Endereços por atendente");
        }
    }//GEN-LAST:event_addEnderecoButtonActionPerformed

    private void confirmarEdicaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEdicaoClienteActionPerformed
        //Vamos Cadastrar um novo fornecedor;
        boolean valido = true;
        AtendenteController controller = new AtendenteController();
        String codigo = codigoAtendenteInput.getText();
        if (codigo.trim().equals("")) {
            valido = false;
        }
        String nome = nomeAtendenteInput.getText();
        if (nome.trim().equals("")) {
            valido = false;
        }
        String login = loginAtendenteInput.getText();
        if (login.trim().equals("")) {
            valido = false;
        }
        String senha = senhaAtendenteInput.getText();
        if (senha.trim().equals("")) {
            valido = false;
        }
        String funcao = funcaoAtendenteInput.getText();
        if (funcao.trim().equals("")) {
            valido = false;
        }
        String nascimento = nascimentoAtendenteInput.getText();
        if (nascimento.trim().equals("")) {
            valido = false;
        }
        String sobrenome = sobrenomeAtendenteInput.getText();
        if (sobrenome.trim().equals("")) {
            valido = false;
        }

        String adimissao = admissaoAtendenteInput.getText();
        if (adimissao.trim().equals("")) {
            valido = false;
        }
        DefaultTableModel tabelaEndereco = (DefaultTableModel) tableEnderecosAtendente.getModel();
        String[][] enderecos = new String[tabelaEndereco.getRowCount()][7];
        //Vamos buscar nossas informacoes da tabela, cada count representa uma row e 0,1,2...5 sao as colunas

        for (int row = 0; row < tabelaEndereco.getRowCount(); row++) {
            if (tabelaEndereco.getValueAt(row, 0) != "") {
                enderecos[row][0] = tabelaEndereco.getValueAt(row, 0).toString();
            } else {
                enderecos[row][0] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 1) != "") {
                enderecos[row][1] = tabelaEndereco.getValueAt(row, 1).toString();
            } else {
                enderecos[row][1] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 2) != "") {
                enderecos[row][2] = tabelaEndereco.getValueAt(row, 2).toString();
            } else {
                enderecos[row][2] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 3) != "") {
                enderecos[row][3] = tabelaEndereco.getValueAt(row, 3).toString();
            } else {
                enderecos[row][3] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 4) != "") {
                enderecos[row][4] = tabelaEndereco.getValueAt(row, 4).toString();
            } else {
                enderecos[row][4] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 5) != "") {
                enderecos[row][5] = tabelaEndereco.getValueAt(row, 5).toString();
            } else {
                enderecos[row][5] = "campoVazio";
            }
            if (tabelaEndereco.getValueAt(row, 6) != "") {
                enderecos[row][6] = tabelaEndereco.getValueAt(row, 6).toString();
            } else {
                enderecos[row][6] = "campoVazio";
            }
        }

        DefaultTableModel tabelaContatos = (DefaultTableModel) tableContatosAtendente.getModel();
        String[][] contatos = new String[tabelaContatos.getRowCount()][3];
        //Vamos buscar nossas informacoes da tabela, cada count representa uma row e 0,1,2...5 sao as colunas
        if (valido) {
            for (int row2 = 0; row2 < tabelaContatos.getRowCount(); row2++) {
                if (tabelaContatos.getValueAt(row2, 0) != "") {
                    contatos[row2][0] = tabelaContatos.getValueAt(row2, 0).toString();
                } else {
                    contatos[row2][0] = "campoVazio";
                }
                if (tabelaContatos.getValueAt(row2, 1) != "") {
                    contatos[row2][1] = tabelaContatos.getValueAt(row2, 1).toString();
                } else {
                    contatos[row2][1] = "campoVazio";
                }
                if (tabelaContatos.getValueAt(row2, 2) != "") {
                    contatos[row2][2] = tabelaContatos.getValueAt(row2, 2).toString();
                } else {
                    contatos[row2][2] = "campoVazio";
                }
            }
        }

        if (valido) {
            String mensagem = controller.editarAtendente(codigo, nome, sobrenome, login, senha, funcao, nascimento, adimissao, enderecos, contatos);
            JOptionPane.showMessageDialog(null, mensagem);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos, verifique o cadastro");
        }
    }//GEN-LAST:event_confirmarEdicaoClienteActionPerformed

    private void removeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeContatoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableContatosAtendente.getModel();
        try {
            int SelectedRowIndex = tableContatosAtendente.getSelectedRow();
            int SelectedsRows = tableContatosAtendente.getSelectedRowCount();
            if (SelectedsRows == 1) {
                model.removeRow(SelectedRowIndex);
            } else if (SelectedsRows > 1) {
                JOptionPane.showMessageDialog(null, "Para garantir uma exclusão mais segura, selecione apenas um linha por vez");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para exclusão");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_removeContatoActionPerformed

    private void cancelarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastroClienteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarCadastroClienteActionPerformed

    private void removeEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnderecoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableEnderecosAtendente.getModel();
        try {
            int SelectedRowIndex = tableEnderecosAtendente.getSelectedRow();
            int SelectedsRows = tableEnderecosAtendente.getSelectedRowCount();
            if (SelectedsRows == 1) {
                model.removeRow(SelectedRowIndex);
            } else if (SelectedsRows > 1) {
                JOptionPane.showMessageDialog(null, "Para garantir uma exclusão mais segura, selecione apenas um linha por vez");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para exclusão");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_removeEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarAtendente dialog = new EditarAtendente(new javax.swing.JFrame(), true, new Atendente());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContatoButtonAtendente;
    private javax.swing.JButton addEnderecoButton;
    private javax.swing.JTextField admissaoAtendenteInput;
    private javax.swing.JButton cancelarCadastroCliente;
    private javax.swing.JTextField codigoAtendenteInput;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JButton confirmarEdicaoCliente;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField funcaoAtendenteInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField loginAtendenteInput;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nascimentoAtendenteInput;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JLabel nascimentoLabel1;
    private javax.swing.JTextField nomeAtendenteInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton removeContato;
    private javax.swing.JButton removeEndereco;
    private javax.swing.JPasswordField senhaAtendenteInput;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JSeparator separadorFooter;
    private javax.swing.JTextField sobrenomeAtendenteInput;
    private javax.swing.JLabel sobrenomeLabel;
    private javax.swing.JTable tableContatosAtendente;
    private javax.swing.JTable tableEnderecosAtendente;
    // End of variables declaration//GEN-END:variables
}
