package View;

import Controller.ProdutoController;
import Model.Produto;
import javax.swing.JOptionPane;

public class EditarProduto extends javax.swing.JDialog {
    
    Produto produtoEdicao;
    /**
     * Creates new form EditarProduto
     */
    public EditarProduto(java.awt.Frame parent, boolean modal, Produto produtoEdicao) {
        super(parent, modal);
        initComponents();
        this.setProdutoEdicao(produtoEdicao);
        loadModelToView(produtoEdicao);
    }
    
    public void setProdutoEdicao(Produto produtoEdicao) {
        this.produtoEdicao = produtoEdicao;
    }
    private void loadModelToView(Produto produtoEdicao) {
        this.codigoProdutoInput.setText(produtoEdicao.getCodigo());
        this.fornecedorProdutoInput.setText(produtoEdicao.getPai().getCodigo() + "-" + produtoEdicao.getPai().getNome());
        this.nomeProdutoInput.setText(produtoEdicao.getNome());
        this.descricaoProdutoInput.setText(produtoEdicao.getDescricao());
        this.precoVendaProdutoInput.setText(this.produtoEdicao.getPrecoVenda().toString());
        this.precoCompraProdutoInput.setText(this.produtoEdicao.getPrecoCompra().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeProdutoInput = new javax.swing.JTextField();
        precoVendaProdutoInput = new javax.swing.JTextField();
        precoCompraProdutoInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoProdutoInput = new javax.swing.JTextArea();
        findFornecedor = new javax.swing.JButton();
        cancelarCadastroProduto = new javax.swing.JButton();
        codigoLabel = new javax.swing.JLabel();
        confirmarEdicaoProduto = new javax.swing.JButton();
        fornecedorLabel = new javax.swing.JLabel();
        separadorFooter = new javax.swing.JSeparator();
        nomeLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        precoVendaLabel = new javax.swing.JLabel();
        precoCompraLabel = new javax.swing.JLabel();
        codigoProdutoInput = new javax.swing.JTextField();
        fornecedorProdutoInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        precoVendaProdutoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoVendaProdutoInputActionPerformed(evt);
            }
        });

        descricaoProdutoInput.setColumns(20);
        descricaoProdutoInput.setRows(5);
        jScrollPane1.setViewportView(descricaoProdutoInput);

        findFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/findIcon.png"))); // NOI18N
        findFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFornecedorActionPerformed(evt);
            }
        });

        cancelarCadastroProduto.setBackground(new java.awt.Color(255, 51, 51));
        cancelarCadastroProduto.setText("Cancelar");
        cancelarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCadastroProdutoActionPerformed(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoLabel.setText("Código:*");

        confirmarEdicaoProduto.setBackground(new java.awt.Color(0, 153, 0));
        confirmarEdicaoProduto.setText("Editar");
        confirmarEdicaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEdicaoProdutoActionPerformed(evt);
            }
        });

        fornecedorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fornecedorLabel.setText("Fornecedor:*");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome:*");

        descricaoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricaoLabel.setText("Descrição:*");

        precoVendaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoVendaLabel.setText("Preço Venda:*");

        precoCompraLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoCompraLabel.setText("Preço Compra:");

        codigoProdutoInput.setEditable(false);
        codigoProdutoInput.setBackground(new java.awt.Color(206, 211, 208));
        codigoProdutoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoInputActionPerformed(evt);
            }
        });

        fornecedorProdutoInput.setEditable(false);
        fornecedorProdutoInput.setBackground(new java.awt.Color(206, 211, 208));
        fornecedorProdutoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorProdutoInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separadorFooter, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(precoVendaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoVendaProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(precoCompraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoCompraProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomeLabel)
                                    .addComponent(fornecedorLabel)
                                    .addComponent(descricaoLabel)
                                    .addComponent(codigoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(fornecedorProdutoInput)
                                        .addGap(18, 18, 18)
                                        .addComponent(findFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomeProdutoInput)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                                    .addComponent(codigoProdutoInput))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(cancelarCadastroProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(confirmarEdicaoProduto)
                            .addGap(12, 12, 12)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoLabel)
                        .addComponent(codigoProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fornecedorLabel)
                                .addComponent(fornecedorProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(findFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeLabel)
                        .addComponent(nomeProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descricaoLabel)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precoVendaLabel)
                        .addComponent(precoVendaProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precoCompraLabel)
                        .addComponent(precoCompraProdutoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addComponent(separadorFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelarCadastroProduto)
                        .addComponent(confirmarEdicaoProduto))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precoVendaProdutoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoVendaProdutoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoVendaProdutoInputActionPerformed

    private void findFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFornecedorActionPerformed
        PesquisarFornecedor pesquisaFornecedor = new PesquisarFornecedor(null, true);
        pesquisaFornecedor.setVisible(true);
        this.fornecedorProdutoInput.setText(pesquisaFornecedor.getRetornaValor());
    }//GEN-LAST:event_findFornecedorActionPerformed

    private void cancelarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCadastroProdutoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarCadastroProdutoActionPerformed

    private void confirmarEdicaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEdicaoProdutoActionPerformed
        //Vamos Cadastrar um novo fornecedor;
        boolean valido = true;
        ProdutoController controller = new ProdutoController();
        String codigo = codigoProdutoInput.getText();
        if (codigo.trim().equals("")) {
            valido = false;
        }
        String codigoFornecedor = fornecedorProdutoInput.getText();
        if (codigoFornecedor.trim().equals("")) {
            valido = false;
        } else {
            String[] partes = codigoFornecedor.split("-");
            codigoFornecedor = partes[0];
        }
        String nome = nomeProdutoInput.getText();
        if (nome.trim().equals("")) {
            valido = false;
        }
        String descricao = descricaoProdutoInput.getText();
        if (descricao.trim().equals("")) {
            valido = false;
        }
        String precoCompra = precoCompraProdutoInput.getText();
        if (precoCompra.trim().equals("")) {
            valido = false;
        }
        String precoVenda = precoVendaProdutoInput.getText();
        if (precoVenda.trim().equals("")) {
            valido = false;
        }

        if (valido) {
            String mensagem = controller.editarProduto(codigo, codigoFornecedor, nome, descricao, precoCompra, precoVenda);
            JOptionPane.showMessageDialog(null, mensagem);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos, verifique o cadastro");
        }
    }//GEN-LAST:event_confirmarEdicaoProdutoActionPerformed

    private void codigoProdutoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoInputActionPerformed

    private void fornecedorProdutoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorProdutoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorProdutoInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarProduto dialog = new EditarProduto(new javax.swing.JFrame(), true, new Produto());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCadastroProduto;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoProdutoInput;
    private javax.swing.JButton confirmarEdicaoProduto;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoProdutoInput;
    private javax.swing.JButton findFornecedor;
    private javax.swing.JLabel fornecedorLabel;
    private javax.swing.JTextField fornecedorProdutoInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeProdutoInput;
    private javax.swing.JLabel precoCompraLabel;
    private javax.swing.JTextField precoCompraProdutoInput;
    private javax.swing.JLabel precoVendaLabel;
    private javax.swing.JTextField precoVendaProdutoInput;
    private javax.swing.JSeparator separadorFooter;
    // End of variables declaration//GEN-END:variables

}
