package View;

public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        canvas1 = new java.awt.Canvas();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        itemMenuFornecedor = new javax.swing.JMenuItem();
        itemMenuCliente = new javax.swing.JMenuItem();
        itemMenuAtendente = new javax.swing.JMenuItem();
        itemMenuProduto = new javax.swing.JMenuItem();
        menuEdicoes = new javax.swing.JMenu();
        itemMenuFornecedorEdicao = new javax.swing.JMenuItem();
        itemMenuClienteEdicao = new javax.swing.JMenuItem();
        itemMenuAtendenteEdicao = new javax.swing.JMenuItem();
        itemMenuProdutoEdicao = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        itemMenuEfetuarVenda = new javax.swing.JMenuItem();
        itemMenuListarVendas = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 180, 180));

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuCadastros.setText("Cadastros");
        menuCadastros.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        menuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrosMouseClicked(evt);
            }
        });

        itemMenuFornecedor.setText("Fornecedor");
        itemMenuFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMenuFornecedorMouseClicked(evt);
            }
        });
        itemMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFornecedorActionPerformed(evt);
            }
        });
        menuCadastros.add(itemMenuFornecedor);

        itemMenuCliente.setText("Cliente");
        itemMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(itemMenuCliente);

        itemMenuAtendente.setText("Atendente");
        itemMenuAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtendenteActionPerformed(evt);
            }
        });
        menuCadastros.add(itemMenuAtendente);

        itemMenuProduto.setText("Produto");
        itemMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(itemMenuProduto);

        jMenuBar2.add(menuCadastros);

        menuEdicoes.setText("Edições");
        menuEdicoes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        itemMenuFornecedorEdicao.setText("Fornecedor");
        itemMenuFornecedorEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFornecedorEdicaoActionPerformed(evt);
            }
        });
        menuEdicoes.add(itemMenuFornecedorEdicao);

        itemMenuClienteEdicao.setText("Cliente");
        itemMenuClienteEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteEdicaoActionPerformed(evt);
            }
        });
        menuEdicoes.add(itemMenuClienteEdicao);

        itemMenuAtendenteEdicao.setText("Atendente");
        itemMenuAtendenteEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtendenteEdicaoActionPerformed(evt);
            }
        });
        menuEdicoes.add(itemMenuAtendenteEdicao);

        itemMenuProdutoEdicao.setText("Produto");
        itemMenuProdutoEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProdutoEdicaoActionPerformed(evt);
            }
        });
        menuEdicoes.add(itemMenuProdutoEdicao);

        jMenuBar2.add(menuEdicoes);

        menuVendas.setText("Vendas");
        menuVendas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        itemMenuEfetuarVenda.setText("Efetuar Venda");
        itemMenuEfetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEfetuarVendaActionPerformed(evt);
            }
        });
        menuVendas.add(itemMenuEfetuarVenda);

        itemMenuListarVendas.setText("Listar Vendas");
        itemMenuListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuListarVendasActionPerformed(evt);
            }
        });
        menuVendas.add(itemMenuListarVendas);

        jMenuBar2.add(menuVendas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(947, 947, 947)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrosMouseClicked

    private void itemMenuFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMenuFornecedorMouseClicked

    }//GEN-LAST:event_itemMenuFornecedorMouseClicked

    private void itemMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFornecedorActionPerformed
        CadastroFornecedor cadastroFornecedor = new CadastroFornecedor(this, rootPaneCheckingEnabled);
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_itemMenuFornecedorActionPerformed

    private void itemMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente(this, rootPaneCheckingEnabled);
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_itemMenuClienteActionPerformed

    private void itemMenuAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtendenteActionPerformed
        CadastroAtendente cadastroAtendente = new CadastroAtendente(this, rootPaneCheckingEnabled);
        cadastroAtendente.setVisible(true);
    }//GEN-LAST:event_itemMenuAtendenteActionPerformed

    private void itemMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProdutoActionPerformed
        CadastroProduto cadastroProduto = new CadastroProduto(this, rootPaneCheckingEnabled);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_itemMenuProdutoActionPerformed

    private void itemMenuEfetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEfetuarVendaActionPerformed
        EfetuarVenda efetuarVenda = new EfetuarVenda(this, rootPaneCheckingEnabled);
        efetuarVenda.setVisible(true);
    }//GEN-LAST:event_itemMenuEfetuarVendaActionPerformed

    private void itemMenuListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuListarVendasActionPerformed
        ListarVendasRealizadas listaVendas = new ListarVendasRealizadas(this, rootPaneCheckingEnabled);
        listaVendas.setVisible(true);
    }//GEN-LAST:event_itemMenuListarVendasActionPerformed

    private void itemMenuFornecedorEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFornecedorEdicaoActionPerformed
        SelecionarEditarFornecedor selecionarEditarFornecedor = new SelecionarEditarFornecedor(this, rootPaneCheckingEnabled);
        selecionarEditarFornecedor.setVisible(true);
    }//GEN-LAST:event_itemMenuFornecedorEdicaoActionPerformed

    private void itemMenuClienteEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteEdicaoActionPerformed
        SelecionarEditarCliente selecionarEditarCliente = new SelecionarEditarCliente(this, rootPaneCheckingEnabled);
        selecionarEditarCliente.setVisible(true);
    }//GEN-LAST:event_itemMenuClienteEdicaoActionPerformed

    private void itemMenuAtendenteEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtendenteEdicaoActionPerformed
        SelecionarEditarAtendente selecionarEditarAtendente = new SelecionarEditarAtendente(this, rootPaneCheckingEnabled);
        selecionarEditarAtendente.setVisible(true);
    }//GEN-LAST:event_itemMenuAtendenteEdicaoActionPerformed

    private void itemMenuProdutoEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProdutoEdicaoActionPerformed
       SelecionarEditarProduto selecionarEditarProduto = new SelecionarEditarProduto(this, rootPaneCheckingEnabled);
       selecionarEditarProduto.setVisible(true);
    }//GEN-LAST:event_itemMenuProdutoEdicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JMenuItem itemMenuAtendente;
    private javax.swing.JMenuItem itemMenuAtendenteEdicao;
    private javax.swing.JMenuItem itemMenuCliente;
    private javax.swing.JMenuItem itemMenuClienteEdicao;
    private javax.swing.JMenuItem itemMenuEfetuarVenda;
    private javax.swing.JMenuItem itemMenuFornecedor;
    private javax.swing.JMenuItem itemMenuFornecedorEdicao;
    private javax.swing.JMenuItem itemMenuListarVendas;
    private javax.swing.JMenuItem itemMenuProduto;
    private javax.swing.JMenuItem itemMenuProdutoEdicao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuEdicoes;
    private javax.swing.JMenu menuVendas;
    // End of variables declaration//GEN-END:variables
}
