package View;

import View.*;
import Controller.ProdutoController;
import Model.Produto;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PesquisarProduto extends javax.swing.JDialog {

    public String retornaValor;
    public String valorDeVenda;

    public String getRetornaValor() {
        return retornaValor;
    }

    public void setRetornaValor(String retornaValor) {
        this.retornaValor = retornaValor;
    }

    public String getValorDeVenda() {
        return valorDeVenda;
    }

    public void setValorDeVenda(String valorDeVenda) {
        this.valorDeVenda = valorDeVenda;
    }
    
    
    /**
     * Creates new form PesquisarFornecedor
     */
    public PesquisarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheComProdutosCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        selecinaFornecedorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Produto");

        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preco Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(produtosTable);

        selecinaFornecedorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/selectIcon.png"))); // NOI18N
        selecinaFornecedorButton.setText("Selecionar");
        selecinaFornecedorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecinaFornecedorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecinaFornecedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selecinaFornecedorButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecinaFornecedorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecinaFornecedorButtonActionPerformed
        //Seleciona a linha da tabela que é o fornecedor selecionado.
        int row = produtosTable.getSelectedRow();
        if (row >= 0) {
            DefaultTableModel fornecedoresTable = (DefaultTableModel) this.produtosTable.getModel();
            String codigo = fornecedoresTable.getValueAt(row, 0).toString();
            String nome = fornecedoresTable.getValueAt(row, 1).toString();
            String precoVenda = fornecedoresTable.getValueAt(row, 2).toString();
            this.setRetornaValor(codigo + "-" + nome);
            this.setValorDeVenda(precoVenda);
            this.setVisible(false);
        }else{
             JOptionPane.showMessageDialog(null, "Selecione uma linha para prosseguir com a selecão de Produto.");
        }
    }//GEN-LAST:event_selecinaFornecedorButtonActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisarProduto dialog = new PesquisarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void preencheComProdutosCadastrados() {
        ProdutoController controller = new ProdutoController();
        ArrayList<Produto> data = controller.selecionarTodosProdutos();
        DefaultTableModel tabela = (DefaultTableModel) produtosTable.getModel();
        for (Produto produto : data) {
            String precoVenda = ""+produto.getPrecoVenda().toString();
            tabela.addRow(new Object[]{produto.getCodigo(), produto.getNome(), precoVenda});
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable produtosTable;
    private javax.swing.JButton selecinaFornecedorButton;
    // End of variables declaration//GEN-END:variables
}
