package View;

import View.*;
import Controller.ProdutoController;
import View.*;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SelecionarEditarProduto extends javax.swing.JDialog {

    public String retornaValor;

    public String getRetornaValor() {
        return retornaValor;
    }

    public void setRetornaValor(String retornaValor) {
        this.retornaValor = retornaValor;
    }

    /**
     * Creates new form SelecionarEditarFornecedor
     */
    public SelecionarEditarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheComProdutosCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        produtoTable = new javax.swing.JTable();
        selecionarEditarAtendenteButton = new javax.swing.JButton();
        selecionarExcluirAtendenteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        produtoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(produtoTable);

        selecionarEditarAtendenteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecionarEditarAtendenteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editIcon.png"))); // NOI18N
        selecionarEditarAtendenteButton.setText("Editar");
        selecionarEditarAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarEditarAtendenteButtonActionPerformed(evt);
            }
        });

        selecionarExcluirAtendenteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecionarExcluirAtendenteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        selecionarExcluirAtendenteButton.setText("Excluir");
        selecionarExcluirAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarExcluirAtendenteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selecionarEditarAtendenteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecionarExcluirAtendenteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarEditarAtendenteButton)
                    .addComponent(selecionarExcluirAtendenteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarExcluirAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarExcluirAtendenteButtonActionPerformed
        int row = produtoTable.getSelectedRow();
        if (row >= 0) {
            int reply = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja realmente excluir este registro?", "Atenção!", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                DefaultTableModel produtoTable = (DefaultTableModel) this.produtoTable.getModel();
                String codigo = produtoTable.getValueAt(row, 0).toString();
                ProdutoController controller = new ProdutoController();
                controller.removerProdutoByCodigo(codigo);
                while (produtoTable.getRowCount() > 0) {
                    produtoTable.removeRow(0);
                }
                preencheComProdutosCadastrados();
            }
        } else if (row < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para prosseguir com a exclusão de Fornecedor.");
        }
    }//GEN-LAST:event_selecionarExcluirAtendenteButtonActionPerformed

    private void selecionarEditarAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarEditarAtendenteButtonActionPerformed
        ProdutoController controller = new ProdutoController();
        int row = produtoTable.getSelectedRow();
        String codigo = produtoTable.getValueAt(row, 0).toString();
        Produto produto = controller.findProdutoByCodigo(codigo);
        EditarProduto edit = new EditarProduto(null, rootPaneCheckingEnabled, produto);
        edit.setVisible(true);
        DefaultTableModel produtoTable = (DefaultTableModel) this.produtoTable.getModel();
        while (produtoTable.getRowCount() > 0) {
            produtoTable.removeRow(0);
        }
        preencheComProdutosCadastrados();
    }//GEN-LAST:event_selecionarEditarAtendenteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelecionarEditarProduto dialog = new SelecionarEditarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void preencheComProdutosCadastrados() {
        ProdutoController controller = new ProdutoController();
        ArrayList<Produto> data = controller.selecionarTodosProdutos();
        DefaultTableModel tabela = (DefaultTableModel) produtoTable.getModel();
        for (Produto produto : data) {
            tabela.addRow(new Object[]{produto.getCodigo().toString(), produto.getNome().toString()});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable produtoTable;
    private javax.swing.JButton selecionarEditarAtendenteButton;
    private javax.swing.JButton selecionarExcluirAtendenteButton;
    // End of variables declaration//GEN-END:variables
}
