/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteController;
import View.*;
import Model.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SelecionarEditarCliente extends javax.swing.JDialog {

    public String retornaValor;

    public String getRetornaValor() {
        return retornaValor;
    }

    public void setRetornaValor(String retornaValor) {
        this.retornaValor = retornaValor;
    }

    /**
     * Creates new form SelecionarEditarFornecedor
     */
    public SelecionarEditarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheComClientesCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        selecionarEditarClienteButton = new javax.swing.JButton();
        selecionarExcluirClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clientesTable);

        selecionarEditarClienteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecionarEditarClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editIcon.png"))); // NOI18N
        selecionarEditarClienteButton.setText("Editar");
        selecionarEditarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarEditarClienteButtonActionPerformed(evt);
            }
        });

        selecionarExcluirClienteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecionarExcluirClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/removeIcon.png"))); // NOI18N
        selecionarExcluirClienteButton.setText("Excluir");
        selecionarExcluirClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarExcluirClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selecionarEditarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecionarExcluirClienteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarEditarClienteButton)
                    .addComponent(selecionarExcluirClienteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarExcluirClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarExcluirClienteButtonActionPerformed
        int row = clientesTable.getSelectedRow();
        if (row >= 0) {
            int reply = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja realmente excluir este registro?", "Atenção!", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                DefaultTableModel clientesTable = (DefaultTableModel) this.clientesTable.getModel();
                String codigo = clientesTable.getValueAt(row, 0).toString();
                ClienteController controller = new ClienteController();
                controller.removerClienteByCodigo(codigo);
                while (clientesTable.getRowCount() > 0) {
                    clientesTable.removeRow(0);
                }
                preencheComClientesCadastrados();
            }
        } else if (row < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para prosseguir com a exclusão de Fornecedor.");
        }
    }//GEN-LAST:event_selecionarExcluirClienteButtonActionPerformed

    private void selecionarEditarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarEditarClienteButtonActionPerformed
        ClienteController controller = new ClienteController();
        int row = clientesTable.getSelectedRow();
        String codigo = clientesTable.getValueAt(row, 0).toString();
        Cliente cliente = controller.findClienteByCodigo(codigo);
        EditarCliente edit = new EditarCliente(null, rootPaneCheckingEnabled, cliente);
        edit.setVisible(true);
        DefaultTableModel fornecedorTable = (DefaultTableModel) this.clientesTable.getModel();
        while (fornecedorTable.getRowCount() > 0) {
            fornecedorTable.removeRow(0);
        }
        preencheComClientesCadastrados();
    }//GEN-LAST:event_selecionarEditarClienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelecionarEditarCliente dialog = new SelecionarEditarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void preencheComClientesCadastrados() {
        ClienteController controller = new ClienteController();
        ArrayList<Cliente> data = controller.selecionarTodosClientes();
        DefaultTableModel tabela = (DefaultTableModel) clientesTable.getModel();
        for (Cliente cliente : data) {
            tabela.addRow(new Object[]{cliente.getCodigo().toString(), cliente.getCpf().toString(), cliente.getNome().toString() +' '+cliente.getSobrenome()});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selecionarEditarClienteButton;
    private javax.swing.JButton selecionarExcluirClienteButton;
    // End of variables declaration//GEN-END:variables
}
